apiVersion: v1
kind: Service
metadata:
  name: testpoject-service
spec:
  ports:
    - name: "8080"
      port: 8082
      nodePort: 30082
      targetPort: 8080
  selector:
    app: testpoject
  type: NodePort
